config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  # As a user, I can edit a task (mark as completed / update title & details)
  # As a user, I can remove a task

  # Read all
  get "/tasks", to: "tasks#index"

  # # Create
  get "/tasks/new", to: "tasks#new", as: :new_task
  post "/tasks", to: "tasks#create"

  # Update
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  # Read one
  get "tasks/:id", to: "tasks#show", as: :task


  # Delete
  delete "tasks/:id", to: "tasks#destroy"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div>
  <h1>Edit task</h1>
</div>

<div>
  <%= form_with model: @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.label :completed %>
    <%= f.check_box  :completed %>
    <%= f.submit %>
  <% end %>
</div>

<div>
  <%= link_to "Go back to list", tasks_path%>
</div>

app/views/tasks/index.html.erb
<div>
  <h1>My tasks</h1>
</div>

<div>
<% @tasks.each do |task| %>
    <div>
      <% if task.completed %>
        <input type="checkbox" id="task" name="task" checked />
      <% else %>
        <input type="checkbox" id="task" name="task"/>
      <% end %>
      <label for="task"><%= link_to "#{task.title}", task_path(task)%></label>
    </div>
  <% end %>
</div>

<div>
  <%= link_to "Create a new task", new_task_path%>
</div>

app/views/tasks/new.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<div>
  <h1><%= @task.title %></h1>
</div>

<div>
  <%= link_to "Edit this task", edit_task_path %>
</div>

<div>
  <label for="task"><%= @task.details %></label>
</div>
<div>
  <% if @task.completed %>
    <input type="checkbox" id="task" name="task" checked />This task is completed
  <% else %>
    <input type="checkbox" id="task" name="task"/>This task isn't completed
  <% end %>
  <%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
</div>

<div>
  <%= link_to "Go back to list", tasks_path%>
</div>